import flet as ft

# --- Configuración de Colores ---
COLOR_PRIMARIO_DORADO = "#FFC72C"
COLOR_FONDO_GRIS_PERLADO = "#F9F9F9"
COLOR_TEXTO_NEGRO = "#212121"
COLOR_TEXTO_SECUNDARIO = "#5C5C5C"
COLOR_FONDO_CARD = "#FFFFFF"


ListaCentro = [
    {"Destino": "100 CASAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "13 DE JULIO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "18 DE NOVIEMBRE", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "SEGUNDA REGION NAVAL", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "22 DE NOVIEMBRE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "23 DE MARZO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "5 DE MAYO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "AMP MIGUEL HIDALGO", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "AMP INDEPENDENCIA", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "AMPLIACION MIGUEL HIDALGO", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "AMPLIACION INDEPENDENCIA", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "ARANJUEZ", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "ASTILLERO NAVAL", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "BARADERO NACIONAL", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "BRISAS DE MIRAMAR", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "BUENOS AIRES", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "BUROCRATA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "CANTERA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "CENTINELA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "CENTRO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "CERRO GANDAREÑO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CASA BLANCA HOTEL", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "CET DEL MAR", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "CET MAR", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "COL GUADALUPE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "COLINAS DE FATIMA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "COLINAS DE MIRAMAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "COSTA AZUL", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CITY EXPRESS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CINEMEX", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "EL CENTENARIO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "EL DELFINARIO", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "EL DORADO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "EL MIRADOR", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "EL PARAJE", "Tarifa": 190.00, "Distancia": ""},
    {"Destino": "EL RESBALON", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "EL VALIENTE", "Tarifa": 280.00, "Distancia": ""},
    {"Destino": "ESTADIO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "FATIMA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "FATIMA RANCHITO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "FOVISSTE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "FRACCIONAMIENTO SONORA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "GIL SAMANIEGO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "GOLFO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "GOLONDRINAS", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "GUARDIA NACIONAL", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "GUARIDA DEL TIGRE", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "GUAYMAS NORTE", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "HOSPITAL NAVAL", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "INDEPENDENCIA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "AEROPUERTO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "ITSON", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LA ANTENA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LA POPULAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LA SALVACION", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "LAS AMERICAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS BATUECAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LAS BRISAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS COLINAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS DELICIAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS FLORES", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS JUNTAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS PALMAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS PERLAS DE MIRAMAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS PLAYITAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS PLAZAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS QUINTAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS TINAJAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS VILLAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LEY VIGIA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LOMA BONITA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LOMA DORADA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LOMA LINDA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LOMAS DE COLOSIO", "Tarifa": 170.00, "Distancia": ""},
    {"Destino": "LOMAS DE CORTEZ", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LOMAS DE MIRAMAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOPEZ MATEOS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOS ARRIEROS", "Tarifa": 850.00, "Distancia": ""},
    {"Destino": "LOS RIOS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "MAQUILAS ROCA FUERTE", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "MIRAMAR EL VENENO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "MISION DEL SOL", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "MONTE LOLITA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "NIZA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "MARSELLA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "PERIODISTAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "PETROLERA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "PLAYA VISTA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "PRIVADAS DE CORTES", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "PUENTE DOUGLAS", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "PUNTA ARENA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "RASTRO CERRO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "RASTRO PLAYA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "REAL OBSSESION HOTEL", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "SAHUARI", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "SAHUARIPA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "SAN BERNARDO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SEGUNDO CIRCLE K", "Tarifa": 250.00, "Distancia": ""},
    {"Destino": "SAN CARLOS ALGODONES", "Tarifa": 450.00, "Distancia": ""},
    {"Destino": "SAN CARLOS COUNTRY", "Tarifa": 270.00, "Distancia": ""},
    {"Destino": "SAN CARLOS HOSPITAL SAN JOSE", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 1", "Tarifa": 550.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 2", "Tarifa": 550.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LEY EXPRESS", "Tarifa": 260.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA REAL", "Tarifa": 400.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA TERRA", "Tarifa": 300.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MIRADOR", "Tarifa": 450.00, "Distancia": ""},
    {"Destino": "SAN CARLOS PLAYA BLANCA", "Tarifa": 500.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SAWARI HOTEL", "Tarifa": 300.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SECTOR BAHIA", "Tarifa": 350.00, "Distancia": ""},
    {"Destino": "SAN CARLOS VILLA BEMELA", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "SAN JOSE", "Tarifa": 170.00, "Distancia": ""},
    {"Destino": "SAN JUDAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "SANTA CLARA", "Tarifa": 230.00, "Distancia": ""},
    {"Destino": "SELECTA ROCA FUERTE", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "TERMOELECTRICA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "TETABIATE", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "VILLAS DE MIRAMAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "VILLAS DEL TULAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "YUCATAN", "Tarifa": 50.00, "Distancia": ""}
]
ListaGuaymasNorte = [
    {"Destino": "GUAYMAS NORTE - 1 DESTINO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "GUAYMAS NORTE - 2 DESTINO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "GUAYMAS NORTE - 3 DESTINO", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "GUAYMAS NORTE - 4 DESTINO", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "100 CASAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "13 DE JULIO", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "18 DE NOVIEMBRE", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "SEGUNDA REGION NAVAL", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "22 DE NOVIEMBRE", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "23 DE MARZO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "5 DE MAYO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "AMP MIGUEL HIDALGO", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "AMP INDEPENDENCIA", "Tarifa": 110.0, "Distancia": ""},
    {"Destino": "AMPLIACION MIGUEL HIDALGO", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "AMPLIACION INDEPENDENCIA", "Tarifa": 110.0, "Distancia": ""},
    {"Destino": "ARANJUEZ", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "ASTILLERO NAVAL", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "BARADERO NACIONAL", "Tarifa": 170.00, "Distancia": ""},
    {"Destino": "BRISAS DE MIRAMAR", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "BUENOS AIRES", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "BUROCRATA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CANTERA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "CENTINELA", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "CENTRO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CERRO GANDAREÑO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CASA BLANCA HOTEL", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "CET DEL MAR", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "CET MAR", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "CITY EXPRESS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CINEMEX", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "COL. GUADALUPE", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "COLINAS DE FATIMA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "COLINAS DE MIRAMAR", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "COSTA AZUL", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "EL CENTENARIO", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "EL DELFINARIO", "Tarifa": 140.00, "Distancia": ""},
    {"Destino": "EL DORADO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "EL MIRADOR", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "EL PARAJE", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "EL RESBALON", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "EL VALIENTE", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "ESTADIO", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "FATIMA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "FATIMA RANCHITO", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "FOVISSTE", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "FRACC. SONORA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "GIL SAMANIEGO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "GOLFO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "GOLONDRINAS", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "GUARDIA NACIONAL", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "GUARIDA DEL TIGRE", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "HOSPITAL NAVAL", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "INDEPENDENCIA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "AEROPUERTO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "ITSON","Tarifa": 50.00, "Distancia": ""},
    {"Destino": "LA ANTENA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LA POPULAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LA SALVACION", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS AMERICAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS BATUECAS", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "LAS BRISAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS COLINAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LAS DELICIAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS FLORES", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS JUNTAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS PALMAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS PERLAS DE MIRAMAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS PLAYITAS", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "LAS PLAZAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS QUINTAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS TINAJAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS VILLAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LEY VIGIA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LOMA BONITA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LOMA DORADA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LOMA LINDA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "LOMAS DE COLOSIO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOMAS DE CORTEZ", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LOMAS DE MIRAMAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOPEZ MATEOS", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "LOS ARRIEROS", "Tarifa": 800.00, "Distancia": ""},
    {"Destino": "LOS RIOS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "MAQUILAS ROCA FUERTE", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "MIRAMAR EL VENENO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "MISION DEL SOL", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "MONTE LOLITA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "NIZA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "MARSELLA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "PERIODISTAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "PETROLERA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "PLAYA VISTA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "PRIVADAS DE CORTES", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "PUENTE DOUGLAS", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "PUNTA ARENA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "RASTRO CERRO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "RASTRO PLAYA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "REAL OBSSESION HOTEL", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "SAHUARI", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "SAHUARIPA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "SAN BERNARDO", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "SAN CARLOS 2DO CIRCLE K", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "SAN CARLOS ALGODONES", "Tarifa": 400.00, "Distancia": ""},
    {"Destino": "SAN CARLOS COUNTRY", "Tarifa": 220.00, "Distancia": ""},
    {"Destino": "SAN CARLOS HOSPITAL SAN JOSE", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 1", "Tarifa": 500.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 2", "Tarifa": 500.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LEY EXPRESS", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA REAL", "Tarifa": 350.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA TERRA", "Tarifa": 250.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MIRADOR", "Tarifa": 400.00, "Distancia": ""},
    {"Destino": "SAN CARLOS PLAYA BLANCA", "Tarifa": 400.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SAWARI HOTEL", "Tarifa": 250.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SECTOR BAHIA", "Tarifa": 300.00, "Distancia": ""},
    {"Destino": "SAN CARLOS VILLA BEMELA", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "SAN JOSE", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "SAN JUDAS", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "SANTA CLARA", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "SELECTA ROCA FUERTE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "TERMOELECTRICA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "TETABIATE", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "VILLAS DE MIRAMAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "VILLAS DEL TULAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "YUCATAN", "Tarifa": 80.00, "Distancia": ""}
]
ListaPetroleraLomaLinda =[
    {"Destino": "100 CASAS", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "13 DE JULIO", "Tarifa": 110.0, "Distancia": ""},
    {"Destino": "18 DE NOVIEMBRE", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "SEGUNDA REGION NAVAL", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "22 DE NOVIEMBRE", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "23 DE MARZO", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "5 DE MAYO", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "AMP MIGUEL HIDALGO", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "AMP INDEPENDENCIA", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "AMPLIACION MIGUEL HIDALGO", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "AMPLIACION INDEPENDENCIA", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "ARANJUEZ", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "ASTILLERO NAVAL", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "BARADERO NACIONAL", "Tarifa": 150.0, "Distancia": ""},
    {"Destino": "BRISAS DE MIRAMAR", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "BUENOS AIRES", "Tarifa": 150.0, "Distancia": ""},
    {"Destino": "BUROCRATA", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "CANTERA", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "CENTINELA", "Tarifa": 110.0, "Distancia": ""},
    {"Destino": "CENTRO", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "CERRO GANDAREÑO", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "CASA BLANCA HOTEL", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "CET DEL MAR", "Tarifa": 110.0, "Distancia": ""},
    {"Destino": "CET MAR", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "COL GUADALUPE", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "COLINAS DE FATIMA", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "COLINAS DE MIRAMAR", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "COSTA AZUL", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "CITY EXPRESS", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "CINEMEX", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "EL CENTENARIO", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "EL DELFINARIO", "Tarifa": 130.0, "Distancia": ""},
    {"Destino": "EL DORADO", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "EL MIRADOR", "Tarifa": 110.0, "Distancia": ""},
    {"Destino": "EL PARAJE", "Tarifa": 180.0, "Distancia": ""},
    {"Destino": "EL RESBALON", "Tarifa": 130.0, "Distancia": ""},
    {"Destino": "EL VALIENTE", "Tarifa": 200.0, "Distancia": ""},
    {"Destino": "ESTADIO", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "FATIMA", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "FATIMA RANCHITO", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "FOVISSTE", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "FRACC. SONORA", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "GIL SAMANIEGO", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "GOLFO", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "GOLONDRINAS", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "GUARDIA NACIONAL", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "GUARIDA DEL TIGRE", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "GUAYMAS NORTE", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "HOSPITAL NAVAL", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "INDEPENDENCIA", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "AEROPUERTO", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "ITSON", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "LA ANTENA", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "LA POPULAR", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "LA SALVACION", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "LAS AMERICAS", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "LAS BATUECAS", "Tarifa": 120.0, "Distancia": ""},
    {"Destino": "LAS BRISAS", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "LAS COLINAS", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "LAS DELICIAS", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "LAS FLORES", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "LAS JUNTAS", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "LAS PALMAS", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "LAS PERLAS DE MIRAMAR", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "LAS PLAYITAS", "Tarifa": 110.0, "Distancia": ""},
    {"Destino": "LAS PLAZAS", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "LAS QUINTAS", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "LAS TINAJAS", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "LAS VILLAS", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "LEY VIGIA", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "LOMA BONITA", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "LOMA DORADA", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "LOMA LINDA", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "LOMAS DE COLOSIO", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "LOMAS DE CORTEZ", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "LOMAS DE MIRAMAR", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "LOPEZ MATEOS", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "LOS ARRIEROS", "Tarifa": 800.0, "Distancia": ""},
    {"Destino": "LOS RIOS", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "MAQUILAS ROCA FUERTE", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "MIRAMAR EL VENENO", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "MISION DEL SOL", "Tarifa": 110.0, "Distancia": ""},
    {"Destino": "MONTE LOLITA", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "NIZA", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "MARSELLA", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "PERIODISTAS", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "PETROLERA", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "PLAYA VISTA", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "PRIVADAS DE CORTES", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "PUENTE DOUGLAS", "Tarifa": 150.0, "Distancia": ""},
    {"Destino": "PUNTA ARENA", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "RASTRO CERRO", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "RASTRO PLAYA", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "REAL OBSSESION HOTEL", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "SAHUARI", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "SAHUARIPA", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "SAN BERNARDO", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "SAN CARLOS SEGUNDO CIRCLE K", "Tarifa": 200.0, "Distancia": ""},
    {"Destino": "SAN CARLOS ALGODONES", "Tarifa": 400.0, "Distancia": ""},
    {"Destino": "SAN CARLOS COUNTRY", "Tarifa": 220.0, "Distancia": ""},
    {"Destino": "SAN CARLOS HOSPITAL SAN JOSE", "Tarifa": 150.0, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 1", "Tarifa": 500.0, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 2", "Tarifa": 500.0, "Distancia": ""},
    {"Destino": "SAN CARLOS LEY EXPRESS", "Tarifa": 200.0, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA REAL", "Tarifa": 350.0, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA TERRA", "Tarifa": 250.0, "Distancia": ""},
    {"Destino": "SAN CARLOS MIRADOR", "Tarifa": 400.0, "Distancia": ""},
    {"Destino": "SAN CARLOS PLAYA BLANCA", "Tarifa": 400.0, "Distancia": ""},
    {"Destino": "SAN CARLOS SAWARI HOTEL", "Tarifa": 250.0, "Distancia": ""},
    {"Destino": "SAN CARLOS SECTOR BAHIA", "Tarifa": 300.0, "Distancia": ""},
    {"Destino": "SAN CARLOS VILLA BEMELA", "Tarifa": 150.0, "Distancia": ""},
    {"Destino": "SAN JOSE", "Tarifa": 130.0, "Distancia": ""},
    {"Destino": "SAN JUDAS", "Tarifa": 120.0, "Distancia": ""},
    {"Destino": "SANTA CLARA", "Tarifa": 150.0, "Distancia": ""},
    {"Destino": "SELECTA ROCA FUERTE", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "TERMOELECTRICA", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "TETABIATE", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "VILLAS DE MIRAMAR", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "VILLAS DEL TULAR", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "YUCATAN", "Tarifa": 70.0, "Distancia": ""}
]
ListaFovissteYAsociadas = [
    {"Destino": "100 CASAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "13 DE JULIO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "18 DE NOVIEMBRE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "SEGUNDA REGION NAVAL", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "22 DE NOVIEMBRE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "23 DE MARZO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "5 DE MAYO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "AMP MIGUEL HIDALGO", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "AMP INDEPENDENCIA", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "AMPLIACION MIGUEL HIDALGO", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "AMPLIACION INDEPENDENCIA", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "ARANJUEZ", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "ASTILLERO NAVAL", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "BARADERO NACIONAL", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "BRISAS DE MIRAMAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "BUENOS AIRES", "Tarifa": 170.00, "Distancia": ""},
    {"Destino": "BUROCRATA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CANTERA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "CENTINELA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "CENTRO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CERRO GANDAREÑO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CASA BLANCA HOTEL", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "CET DEL MAR", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "COL. GUADALUPE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "COLINAS DE FATIMA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "COLINAS DE MIRAMAR", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "COSTA AZUL", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "CITY EXPRESS", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "CINEMEX", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "EL CENTENARIO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "EL DELFINARIO", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "EL DORADO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "EL MIRADOR", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "EL PARAJE", "Tarifa": 160.00, "Distancia": ""},
    {"Destino": "EL RESBALON", "Tarifa": 140.00, "Distancia": ""},
    {"Destino": "EL VALIENTE", "Tarifa": 220.00, "Distancia": ""},
    {"Destino": "ESTADIO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "FATIMA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "FATIMA RANCHITO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "FOVISSTE", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "FRACC. SONORA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "GIL SAMANIEGO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "GOLFO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "GOLONDRINAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "GUARDIA NACIONAL", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "GUARIDA DEL TIGRE", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "GUAYMAS NORTE", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "HOSPITAL NAVAL", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "INDEPENDENCIA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "AEROPUERTO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "ITSON", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LA ANTENA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LA POPULAR", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LA SALVACION", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "LOS ARRIEROS", "Tarifa": 820.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 1", "Tarifa": 520.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 2", "Tarifa": 520.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LEY EXPRESS", "Tarifa": 230.0, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA REAL", "Tarifa": 370.0, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA TERRA", "Tarifa": 270.0, "Distancia": ""},
    {"Destino": "SAN CARLOS MIRADOR", "Tarifa": 420.0, "Distancia": ""},
    {"Destino": "SAN CARLOS PLAYA BLANCA", "Tarifa": 470.0, "Distancia": ""},
    {"Destino": "SAN CARLOS SAWARI HOTEL", "Tarifa": 270.0, "Distancia": ""},
    {"Destino": "SAN CARLOS SECTOR BAHIA", "Tarifa": 320.0, "Distancia": ""},
    {"Destino": "SAN CARLOS VILLA BEMELA", "Tarifa": 170.0, "Distancia": ""},
    {"Destino": "SAN JOSE", "Tarifa": 140.0, "Distancia": ""},
    {"Destino": "SAN JUDAS", "Tarifa": 110.0, "Distancia": ""},
    {"Destino": "SANTA CLARA", "Tarifa": 170.0, "Distancia": ""},
    {"Destino": "SELECTA ROCA FUERTE", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "TERMOELECTRICA", "Tarifa": 90.0, "Distancia": ""},
    {"Destino": "TETABIATE", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "VILLAS DE MIRAMAR", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "VILLAS DEL TULAR", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "YUCATAN", "Tarifa": 60.0, "Distancia": ""}
]
ListaGolondrinasYAsociadas = [
    {"Destino": "100 CASAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "13 DE JULIO", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "18 DE NOVIEMBRE", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "SEGUNDA REGION NAVAL", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "22 DE NOVIEMBRE", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "23 DE MARZO", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "5 DE MAYO", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "AMP MIGUEL HIDALGO", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "AMP INDEPENDENCIA", "Tarifa": 110.0, "Distancia": ""},
    {"Destino": "AMPLIACION MIGUEL HIDALGO", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "AMPLIACION INDEPENDENCIA", "Tarifa": 110.0, "Distancia": ""},
    {"Destino": "ARANJUEZ", "Tarifa": 170.00, "Distancia": ""},
    {"Destino": "ASTILLERO NAVAL", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "BARADERO NACIONAL", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "BRISAS DE MIRAMAR", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "BUENOS AIRES", "Tarifa": 250.00, "Distancia": ""},
    {"Destino": "BUROCRATA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CANTERA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CENTINELA", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "CENTRO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CERRO GANDAREÑO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "CASA BLANCA HOTEL", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "CET DEL MAR", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "CET MAR", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "COL. GUADALUPE", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "FATIMA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "COLINAS DE MIRAMAR", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "COSTA AZUL", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "CINEMEX - CITY EXPRESS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "EL CENTENARIO", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "EL DELFINARIO", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "EL DORADO", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "EL MIRADOR", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "EL PARAJE", "Tarifa": 220.00, "Distancia": ""},
    {"Destino": "EL RESBALON", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "EL VALIENTE", "Tarifa": 310.00, "Distancia": ""},
    {"Destino": "ESTADIO", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "FATIMA RANCHITO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "FOVISSTE", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "FRACC. SONORA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "GIL SAMANIEGO", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "GOLFO", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "GOLONDRINAS", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "GUARDIA NACIONAL", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "GUARIDA DEL TIGRE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "GUAYMAS NORTE", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "HOSPITAL NAVAL", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "INDEPENDENCIA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "AEROPUERTO", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "ITSON", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "LA ANTENA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LA POPULAR", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LA SALVACION", "Tarifa": 170.00, "Distancia": ""},
    {"Destino": "LAS AMERICAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS BATUECAS", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "LAS BRISAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS COLINAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS DELICIAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS FLORES", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS JUNTAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS PALMAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS PERLAS DE MIRAMAR", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS PLAYITAS", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "LAS PLAZAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS QUINTAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS TINAJAS", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "LAS VILLAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LEY VIGIA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOMA BONITA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LOMA DORADA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LOMA LINDA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LOMAS DE COLOSIO", "Tarifa": 160.00, "Distancia": ""},
    {"Destino": "LOMAS DE CORTEZ", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "LOMAS DE MIRAMAR", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "LOPEZ MATEOS", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "LOS ARRIEROS", "Tarifa": 850.00, "Distancia": ""},
    {"Destino": "LOS RIOS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "MAQUILAS ROCA FUERTE", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "MIRAMAR EL VENENO", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "MISION DEL SOL", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "MONTE LOLITA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "MARSELLA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "NIZA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "PERIODISTAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "PETROLERA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "PLAYA VISTA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "PRIVADAS DE CORTES", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "PUENTE DOUGLAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "PUNTA ARENA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "RASTRO CERRO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "RASTRO PLAYA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "REAL OBSSESION", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "SAN VICENTE", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "SAHUARI", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "SAHUARIPA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "SAN BERNARDO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "SAN CARLOS 2DO CIRCLE K", "Tarifa": 270.00, "Distancia": ""},
    {"Destino": "SAN CARLOS ALGODONES", "Tarifa": 470.00, "Distancia": ""},
    {"Destino": "SAN CARLOS COUNTRY", "Tarifa": 290.00, "Distancia": ""},
    {"Destino": "SAN CARLOS HOSPITAL SAN JOSE", "Tarifa": 220.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 1", "Tarifa": 570.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 2", "Tarifa": 570.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LEY EXPRESS", "Tarifa": 280.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA REAL", "Tarifa": 420.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA TERRA", "Tarifa": 320.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MIRADOR", "Tarifa": 470.00, "Distancia": ""},
    {"Destino": "SAN CARLOS PLAYA BLANCA", "Tarifa": 520.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SAWARI HOTEL", "Tarifa": 320.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SECTOR BAHIA", "Tarifa": 370.00, "Distancia": ""},
    {"Destino": "SAN CARLOS VILLA BEMELA", "Tarifa": 220.00, "Distancia": ""},
    {"Destino": "SAN JOSE", "Tarifa": 220.00, "Distancia": ""},
    {"Destino": "SAN JUDAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "SANTA CLARA", "Tarifa": 250.00, "Distancia": ""},
    {"Destino": "SELECTA ROCA FUERTE", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "TERMOELECTRICA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "TETABIATE", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "VILLAS DE MIRAMAR", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "VILLAS DEL TULAR", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "YUCATAN", "Tarifa": 60.00, "Distancia": ""}
]
ListaSanVicente =[
    {"Destino": "100 CASAS", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "13 DE JULIO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "18 DE NOVIEMBRE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "SEGUNDA REGION NAVAL", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "22 DE NOVIEMBRE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "23 DE MARZO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "5 DE MAYO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "AMP MIGUEL HIDALGO", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "AMP INDEPENDENCIA", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "AMPLIACION MIGUEL HIDALGO", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "AMPLIACION INDEPENDENCIA", "Tarifa": 60.0, "Distancia": ""},
    {"Destino": "ARANJUEZ", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "ASTILLERO NAVAL", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "BARADERO NACIONAL", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "BRISAS DE MIRAMAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "BUENOS AIRES", "Tarifa": 230.00, "Distancia": ""},
    {"Destino": "BUROCRATA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CANTERA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "CENTINELA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "CENTRO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CERRO GANDAREÑO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CASA BLANCA HOTEL", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "CET DEL MAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "CET MAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "COL. GUADALUPE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "COLINAS DE FATIMA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "COLINAS DE MIRAMAR", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "COSTA AZUL", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "CITY EXPRESS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "CINEMEX", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "EL CENTENARIO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "EL DELFINARIO", "Tarifa": 140.00, "Distancia": ""},
    {"Destino": "EL DORADO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "EL MIRADOR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "EL PARAJE", "Tarifa": 140.00, "Distancia": ""},
    {"Destino": "EL RESBALON", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "EL VALIENTE", "Tarifa": 280.00, "Distancia": ""},
    {"Destino": "ESTADIO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "FATIMA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "FATIMA RANCHITO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "FOVISSTE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "FRACC. SONORA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "GIL SAMANIEGO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "GOLFO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "GOLONDRINAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "GUARDIA NACIONAL", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "GUARIDA DEL TIGRE", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "GUAYMAS NORTE", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "HOSPITAL NAVAL", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "INDEPENDENCIA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "AEROPUERTO", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "ITSON", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LA ANTENA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "LA POPULAR", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LA SALVACION", "Tarifa": 170.00, "Distancia": ""},
    {"Destino": "LAS AMERICAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS BATUECAS", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "LAS BRISAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS COLINAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS DELICIAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS FLORES", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS JUNTAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS PALMAS", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "LAS PERLAS DE MIRAMAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS PLAYITAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS PLAZAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS QUINTAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS TINAJAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LAS VILLAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LEY VIGIA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LOMA BONITA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LOMA DORADA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LOMA LINDA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LOMAS DE COLOSIO", "Tarifa": 160.00, "Distancia": ""},
    {"Destino": "LOMAS DE CORTEZ", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LOMAS DE MIRAMAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOPEZ MATEOS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LOS ARRIEROS", "Tarifa": 850.00, "Distancia": ""},
    {"Destino": "LOS RIOS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "MAQUILAS ROCA FUERTE", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "MIRAMAR EL VENENO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "MISION DEL SOL", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "MONTE LOLITA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "NIZA - MARSELLA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "PERIODISTAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "PETROLERA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "PLAYA VISTA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "PRIVADAS DE CORTES", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "PUENTE DOUGLAS", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "PUNTA ARENA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "RASTRO CERRO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "RASTRO PLAYA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "REAL OBSSESION HOTEL", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "SAHUARI", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "SAHUARIPA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "SAN BERNARDO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "SAN CARLOS 2DO CIRCLE K", "Tarifa": 280.00, "Distancia": ""},
    {"Destino": "SAN CARLOS ALGODONES", "Tarifa": 480.00, "Distancia": ""},
    {"Destino": "SAN CARLOS COUNTRY", "Tarifa": 300.00, "Distancia": ""},
    {"Destino": "SAN CARLOS HOSPITAL SAN JOSE", "Tarifa": 230.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 1", "Tarifa": 580.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 2", "Tarifa": 580.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LEY EXPRESS", "Tarifa": 280.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA REAL", "Tarifa": 430.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA TERRA", "Tarifa": 320.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MIRADOR", "Tarifa": 480.00, "Distancia": ""},
    {"Destino": "SAN CARLOS PLAYA BLANCA", "Tarifa": 480.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SAWARI HOTEL", "Tarifa": 330.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SECTOR BAHIA", "Tarifa": 380.00, "Distancia": ""},
    {"Destino": "SAN CARLOS VILLA BEMELA", "Tarifa": 230.00, "Distancia": ""},
    {"Destino": "SAN JOSE", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "SAN JUDAS", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "SANTA CLARA", "Tarifa": 230.00, "Distancia": ""},
    {"Destino": "SELECTA ROCA FUERTE", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "TERMOELECTRICA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "TETABIATE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "VILLAS DE MIRAMAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "VILLAS DEL TULAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "YUCATAN", "Tarifa": 50.00, "Distancia": ""}
]
Lista18Noviembre23Marzo = [
    {"Destino": "100 CASAS", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "13 DE JULIO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "18 DE NOVIEMBRE", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "SEGUNDA REGION NAVAL", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "22 DE NOVIEMBRE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "23 DE MARZO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "5 DE MAYO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "AMP MIGUEL HIDALGO", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "AMP INDEPENDENCIA", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "AMPLIACION MIGUEL HIDALGO", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "AMPLIACION INDEPENDENCIA", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "ARANJUEZ", "Tarifa": 170.00, "Distancia": ""},
    {"Destino": "ASTILLERO NAVAL", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "BARADERO NACIONAL", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "BRISAS DE MIRAMAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "BUENOS AIRES", "Tarifa": 240.00, "Distancia": ""},
    {"Destino": "BUROCRATA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CANTERA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "CENTINELA", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CENTRO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CERRO GANDAREÑO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CASA BLANCA HOTEL", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "CET DEL MAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CET MAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "COL. GUADALUPE", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "COLINAS DE FATIMA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "COLINAS DE MIRAMAR", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "COSTA AZUL", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CINEMEX - CITY EXPRESS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "EL CENTENARIO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "EL DELFINARIO", "Tarifa": 160.00, "Distancia": ""},
    {"Destino": "EL DORADO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "EL MIRADOR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "EL PARAJE", "Tarifa": 140.00, "Distancia": ""},
    {"Destino": "EL RESBALON", "Tarifa": 190.00, "Distancia": ""},
    {"Destino": "EL VALIENTE", "Tarifa": 290.00, "Distancia": ""},
    {"Destino": "ESTADIO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "FATIMA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "FATIMA RANCHITO", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "FOVISSTE", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "FRACC. SONORA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "GIL SAMANIEGO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "GOLFO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "GOLONDRINAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "GUARDIA NACIONAL", "Tarifa": 190.00, "Distancia": ""},
    {"Destino": "GUARIDA DEL TIGRE", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "GUAYMAS NORTE", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "HOSPITAL NAVAL", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "INDEPENDENCIA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "AEROPUERTO", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "ITSON", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "LA ANTENA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LA POPULAR", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LA SALVACION", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "LAS AMERICAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS BATUECAS", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "LAS BRISAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS COLINAS", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "LAS DELICIAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS FLORES", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS JUNTAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS PALMAS", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "LAS PERLAS DE MIRAMAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LAS PLAYITAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS PLAZAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS QUINTAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS TINAJAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS VILLAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LEY VIGIA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LOMA BONITA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "LOMA DORADA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LOMA LINDA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOMAS DE COLOSIO", "Tarifa": 170.00, "Distancia": ""},
    {"Destino": "LOMAS DE CORTEZ", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOMAS DE MIRAMAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOPEZ MATEOS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LOS ARRIEROS", "Tarifa": 850.00, "Distancia": ""},
    {"Destino": "LOS RIOS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "MAQUILAS ROCA FUERTE", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "MIRAMAR EL VENENO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "MISION DEL SOL", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "MONTE LOLITA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "NIZA - MARSELLA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "PERIODISTAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "PETROLERA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "PLAYA VISTA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "PRIVADAS DE CORTES", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "PUENTE DOUGLAS", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "PUNTA ARENA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "RASTRO CERRO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "RASTRO PLAYA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "REAL OBSSESION HOTEL", "Tarifa": 190.00, "Distancia": ""},
    {"Destino": "SAHUARI", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "SAHUARIPA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "SAN BERNARDO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "SAN CARLOS 2DO CIRCLE K", "Tarifa": 290.00, "Distancia": ""},
    {"Destino": "SAN CARLOS ALGODONES", "Tarifa": 490.00, "Distancia": ""},
    {"Destino": "SAN CARLOS COUNTRY", "Tarifa": 310.00, "Distancia": ""},
    {"Destino": "SAN CARLOS HOSPITAL SAN JOSE", "Tarifa": 240.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 1", "Tarifa": 590.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 2", "Tarifa": 590.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LEY EXPRESS", "Tarifa": 290.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA REAL", "Tarifa": 440.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA TERRA", "Tarifa": 340.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MIRADOR", "Tarifa": 490.00, "Distancia": ""},
    {"Destino": "SAN CARLOS PLAYA BLANCA", "Tarifa": 490.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SAWARI HOTEL", "Tarifa": 340.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SECTOR BAHIA", "Tarifa": 390.00, "Distancia": ""},
    {"Destino": "SAN CARLOS VILLA BEMELA", "Tarifa": 240.00, "Distancia": ""},
    {"Destino": "SAN JOSE", "Tarifa": 190.00, "Distancia": ""},
    {"Destino": "SAN JUDAS", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "SANTA CLARA", "Tarifa": 240.00, "Distancia": ""},
    {"Destino": "SELECTA ROCA FUERTE", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "TERMOELECTRICA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "TETABIATE", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "VILLAS DE MIRAMAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "VILLAS DEL TULAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "YUCATAN", "Tarifa": 70.00, "Distancia": ""}
]
ListaCentinelaYAsociadas =[
    {"Destino": "100 CASAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "13 DE JULIO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "18 DE NOVIEMBRE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "SEGUNDA REGION NAVAL", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "22 DE NOVIEMBRE", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "23 DE MARZO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "5 DE MAYO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "AMP MIGUEL HIDALGO", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "AMP INDEPENDENCIA", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "AMPLIACION MIGUEL HIDALGO", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "AMPLIACION INDEPENDENCIA", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "ARANJUEZ", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "ASTILLERO NAVAL", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "BARADERO NACIONAL", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "BRISAS DE MIRAMAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "BUENOS AIRES", "Tarifa": 250.00, "Distancia": ""},
    {"Destino": "BUROCRATA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CANTERA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CENTINELA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "CENTRO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CERRO GANDAREÑO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CASA BLANCA HOTEL", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "CET DEL MAR", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CET MAR", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "COL. GUADALUPE", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "COLINAS DE FATIMA", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "COLINAS DE MIRAMAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "COSTA AZUL", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CITY EXPRESS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "CINEMEX", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "EL CENTENARIO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "EL DELFINARIO", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "EL DORADO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "EL MIRADOR", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "EL PARAJE", "Tarifa": 140.00, "Distancia": ""},
    {"Destino": "EL RESBALON", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "EL VALIENTE", "Tarifa": 400.00, "Distancia": ""},
    {"Destino": "ESTADIO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "FATIMA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "FATIMA RANCHITO", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "FOVISSTE", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "FRACC. SONORA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "GIL SAMANIEGO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "GOLFO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "GOLONDRINAS", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "GUARDIA NACIONAL", "Tarifa": 210.00, "Distancia": ""},
    {"Destino": "GUARIDA DEL TIGRE", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "GUAYMAS NORTE", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "HOSPITAL NAVAL", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "INDEPENDENCIA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "AEROPUERTO", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "ITSON", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "LA ANTENA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LA POPULAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LA SALVACION", "Tarifa": 190.00, "Distancia": ""},
    {"Destino": "LAS AMERICAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS BATUECAS", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "LAS BRISAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS COLINAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS DELICIAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS FLORES", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS JUNTAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS PALMAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS PERLAS DE MIRAMAR", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS PLAYITAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS PLAZAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LAS QUINTAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LAS TINAJAS", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "LAS VILLAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LEY VIGIA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOMA BONITA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "LOMA DORADA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOMA LINDA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LOMAS DE COLOSIO", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "LOMAS DE CORTEZ", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LOMAS DE MIRAMAR", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LOPEZ MATEOS", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "LOS ARRIEROS", "Tarifa": 900.00, "Distancia": ""},
    {"Destino": "LOS RIOS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "MAQUILAS ROCA FUERTE", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "MIRAMAR EL VENENO", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "MISION DEL SOL", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "MONTE LOLITA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "NIZA - MARSELLA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "PERIODISTAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "PETROLERA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "PLAYA VISTA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "PRIVADAS DE CORTES", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "PUENTE DOUGLAS", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "PUNTA ARENA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "RASTRO CERRO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "RASTRO PLAYA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "REAL OBSSESION HOTEL", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "SAHUARI", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "SAHUARIPA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "SAN BERNARDO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "SAN CARLOS 2DO CIRCLE K", "Tarifa": 320.00, "Distancia": ""},
    {"Destino": "SAN CARLOS ALGODONES", "Tarifa": 520.00, "Distancia": ""},
    {"Destino": "SAN CARLOS COUNTRY", "Tarifa": 340.00, "Distancia": ""},
    {"Destino": "SAN CARLOS HOSPITAL SAN JOSE", "Tarifa": 270.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 1", "Tarifa": 620.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 2", "Tarifa": 620.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LEY EXPRESS", "Tarifa": 320.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA REAL", "Tarifa": 470.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA TERRA", "Tarifa": 370.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MIRADOR", "Tarifa": 520.00, "Distancia": ""},
    {"Destino": "SAN CARLOS PLAYA BLANCA", "Tarifa": 520.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SAWARI HOTEL", "Tarifa": 370.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SECTOR BAHIA", "Tarifa": 420.00, "Distancia": ""},
    {"Destino": "SAN CARLOS VILLA BEMELA", "Tarifa": 270.00, "Distancia": ""},
    {"Destino": "SAN JOSE", "Tarifa": 220.00, "Distancia": ""},
    {"Destino": "SAN JUDAS", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "SANTA CLARA", "Tarifa": 270.00, "Distancia": ""},
    {"Destino": "SELECTA ROCA FUERTE", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "TERMOELECTRICA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "TETABIATE", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "VILLAS DE MIRAMAR", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "VILLAS DEL TULAR", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "YUCATAN", "Tarifa": 70.00, "Distancia": ""}
]
ListaMirador =[
    {"Destino": "100 CASAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "13 DE JULIO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "18 DE NOVIEMBRE", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "SEGUNDA REGION NAVAL", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "22 DE NOVIEMBRE", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "23 DE MARZO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "5 DE MAYO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "AMP MIGUEL HIDALGO", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "AMP INDEPENDENCIA", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "AMPLIACION MIGUEL HIDALGO", "Tarifa": 70.0, "Distancia": ""},
    {"Destino": "AMPLIACION INDEPENDENCIA", "Tarifa": 50.0, "Distancia": ""},
    {"Destino": "ARANJUEZ", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "ASTILLERO NAVAL", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "BARADERO NACIONAL", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "BRISAS DE MIRAMAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "BUENOS AIRES", "Tarifa": 250.00, "Distancia": ""},
    {"Destino": "BUROCRATA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CANTERA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CENTINELA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "CENTRO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CERRO GANDAREÑO", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "CASA BLANCA HOTEL", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "CET DEL MAR", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CET MAR", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "COL GUADALUPE", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "COLINAS DE FATIMA", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "COLINAS DE MIRAMAR", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "COSTA AZUL", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "CITY EXPRESS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "CINEMEX", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "EL CENTENARIO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "EL DELFINARIO", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "EL DORADO", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "EL MIRADOR", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "EL PARAJE", "Tarifa": 140.00, "Distancia": ""},
    {"Destino": "EL RESBALON", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "EL VALIENTE", "Tarifa": 400.00, "Distancia": ""},
    {"Destino": "ESTADIO", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "FATIMA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "FATIMA RANCHITO", "Tarifa": 120.00, "Distancia": ""},
    {"Destino": "FOVISSTE", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "FRACC. SONORA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "GIL SAMANIEGO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "GOLFO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "GOLONDRINAS", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "GUARDIA NACIONAL", "Tarifa": 210.00, "Distancia": ""},
    {"Destino": "GUARIDA DEL TIGRE", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "GUAYMAS NORTE", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "HOSPITAL NAVAL", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "INDEPENDENCIA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "AEROPUERTO", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "ITSON", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "LA ANTENA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LA POPULAR", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LA SALVACION", "Tarifa": 190.00, "Distancia": ""},
    {"Destino": "LAS AMERICAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS BATUECAS", "Tarifa": 150.00, "Distancia": ""},
    {"Destino": "LAS BRISAS", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS COLINAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "LAS DELICIAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS FLORES", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS JUNTAS", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LAS PALMAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS PERLAS DE MIRAMAR", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LAS PLAYITAS", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "LAS PLAZAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LAS QUINTAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LAS TINAJAS", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "LAS VILLAS", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LEY VIGIA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOMA BONITA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "LOMA DORADA", "Tarifa": 80.00, "Distancia": ""},
    {"Destino": "LOMA LINDA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "LOMAS DE COLOSIO", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "LOMAS DE CORTEZ", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LOMAS DE MIRAMAR", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "LOPEZ MATEOS", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "LOS ARRIEROS", "Tarifa": 900.00, "Distancia": ""},
    {"Destino": "LOS RIOS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "MAQUILAS ROCA FUERTE", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "MIRAMAR EL VENENO", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "MISION DEL SOL", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "MONTE LOLITA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "NIZA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "MARSELLA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "PERIODISTAS", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "PETROLERA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "PLAYA VISTA", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "PRIVADAS DE CORTES", "Tarifa": 90.00, "Distancia": ""},
    {"Destino": "PUENTE DOUGLAS", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "PUNTA ARENA", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "RASTRO CERRO", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "RASTRO PLAYA", "Tarifa": 70.00, "Distancia": ""},
    {"Destino": "REAL OBSSESION HOTEL", "Tarifa": 200.00, "Distancia": ""},
    {"Destino": "SAHUARI", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "SAHUARIPA", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "SAN BERNARDO", "Tarifa": 60.00, "Distancia": ""},
    {"Destino": "SAN CARLOS 2DO CIRCLE K", "Tarifa": 320.00, "Distancia": ""},
    {"Destino": "SAN CARLOS ALGODONES", "Tarifa": 520.00, "Distancia": ""},
    {"Destino": "SAN CARLOS COUNTRY", "Tarifa": 340.00, "Distancia": ""},
    {"Destino": "SAN CARLOS HOSPITAL SAN JOSE", "Tarifa": 270.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 1", "Tarifa": 620.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LA MANGA 2", "Tarifa": 620.00, "Distancia": ""},
    {"Destino": "SAN CARLOS LEY EXPRESS", "Tarifa": 320.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA REAL", "Tarifa": 470.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MARINA TERRA", "Tarifa": 370.00, "Distancia": ""},
    {"Destino": "SAN CARLOS MIRADOR", "Tarifa": 520.00, "Distancia": ""},
    {"Destino": "SAN CARLOS PLAYA BLANCA", "Tarifa": 520.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SAWARI HOTEL", "Tarifa": 370.00, "Distancia": ""},
    {"Destino": "SAN CARLOS SECTOR BAHIA", "Tarifa": 420.00, "Distancia": ""},
    {"Destino": "SAN CARLOS VILLA BEMELA", "Tarifa": 270.00, "Distancia": ""},
    {"Destino": "SAN JOSE", "Tarifa": 220.00, "Distancia": ""},
    {"Destino": "SAN JUDAS", "Tarifa": 180.00, "Distancia": ""},
    {"Destino": "SANTA CLARA", "Tarifa": 270.00, "Distancia": ""},
    {"Destino": "SELECTA ROCA FUERTE", "Tarifa": 130.00, "Distancia": ""},
    {"Destino": "TERMOELECTRICA", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "TETABIATE", "Tarifa": 50.00, "Distancia": ""},
    {"Destino": "VILLAS DE MIRAMAR", "Tarifa": 100.00, "Distancia": ""},
    {"Destino": "VILLAS DEL TULAR", "Tarifa": 110.00, "Distancia": ""},
    {"Destino": "YUCATAN", "Tarifa": 70.00, "Distancia": ""}
]
ListaUtg = [
    {"Destino": "18 DE NOVIEMBRE / 23 DE MARZO", "Tarifa": 120.0, "Distancia": ""},
    {"Destino": "CENTINELA", "Tarifa": 150.0, "Distancia": ""},
    {"Destino": "CENTRO", "Tarifa": 120.0, "Distancia": ""},
    {"Destino": "FOVISSTE / AMERICAS / LEY VIGIA / PLAZAS", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "GOLONDRINAS / PTA ARENA / MONTE LOLITA / TERMOELECTRICA", "Tarifa": 140.0, "Distancia": ""},
    {"Destino": "GUAYMAS NORTE", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "LEY VIGIA", "Tarifa": 100.0, "Distancia": ""},
    {"Destino": "MIRADOR", "Tarifa": 150.0, "Distancia": ""},
    {"Destino": "PETROLERA / LOMA LINDA", "Tarifa": 80.0, "Distancia": ""},
    {"Destino": "SAN VICENTE", "Tarifa": 110.0, "Distancia": ""}
]
ListaGnValle = [
    {"Destino": "SAN FERNANDO", "Tarifa": 400.0, "Distancia": ""},
    {"Destino": "LA AGUILITA", "Tarifa": 400.0, "Distancia": ""},
    {"Destino": "LA PALMA", "Tarifa": 450.0, "Distancia": ""},
    {"Destino": "MAYTORENA", "Tarifa": 550.0, "Distancia": ""},
    {"Destino": "URSULO GALVAN", "Tarifa": 550.0, "Distancia": ""},
    {"Destino": "LA ATREVESADA", "Tarifa": 550.0, "Distancia": ""},
    {"Destino": "SANTA MARIA", "Tarifa": 600.0, "Distancia": ""},
    {"Destino": "GRACIANO SANCHES", "Tarifa": 650.0, "Distancia": ""},
    {"Destino": "ORTIZ", "Tarifa": 800.0, "Distancia": ""},
    {"Destino": "ADOLFO DE LA HUERTA", "Tarifa": 800.0, "Distancia": ""},
    {"Destino": "CRUZ DE PIEDRA", "Tarifa": 400.0, "Distancia": ""},
    {"Destino": "LAS GUASIMAS", "Tarifa": 550.0, "Distancia": ""},
    {"Destino": "PITHAYA", "Tarifa": 800.0, "Distancia": ""},
    {"Destino": "RAHUM", "Tarifa": 1000.0, "Distancia": ""},
    {"Destino": "POTAM", "Tarifa": 1000.0, "Distancia": ""},
    {"Destino": "VICAM", "Tarifa": 1000.0, "Distancia": ""},
    {"Destino": "VICAM PUEBLO", "Tarifa": 1100.0, "Distancia": ""},
    {"Destino": "OBREGON", "Tarifa": 2000.0, "Distancia": ""},
    {"Destino": "NAVOJOA", "Tarifa": 2500.0, "Distancia": ""},
    {"Destino": "HERMOSILLO", "Tarifa": 2000.0, "Distancia": ""},
    {"Destino": "AEROPUERTO HERMOSILLO", "Tarifa": 2000.0, "Distancia": ""},
]
ListaGnEmpalme = [
    {"Destino": "BELLA VISTA", "Tarifa": 170.0, "Distancia": ""},
    {"Destino": "MAQUILAS TETAKAWI", "Tarifa": 170.0, "Distancia": ""},
    {"Destino": "KILOMETRO 2", "Tarifa": 170.0, "Distancia": ""},
    {"Destino": "LA RONY", "Tarifa": 200.0, "Distancia": ""},
    {"Destino": "LA PESQUEIRA", "Tarifa": 180.0, "Distancia": ""},
    {"Destino": "LA MODERNA 1", "Tarifa": 200.0, "Distancia": ""},
    {"Destino": "LA MODERNA 2", "Tarifa": 200.0, "Distancia": ""},
    {"Destino": "LA JUAREZ", "Tarifa": 220.0, "Distancia": ""},
    {"Destino": "LA JORDAN ", "Tarifa": 220.0, "Distancia": ""},
    {"Destino": "LA LIBERTAD", "Tarifa": 230.0, "Distancia": ""},
    {"Destino": "LA ORIENTE", "Tarifa": 200.0, "Distancia": ""},
    {"Destino": "LA ORTIZ RUBIO", "Tarifa": 200.0, "Distancia": ""},
    {"Destino": "INFO. GUADALUPE", "Tarifa": 250.0, "Distancia": ""},
    {"Destino": "BAHIA DEL SOL", "Tarifa": 250.0, "Distancia": ""},
    {"Destino": "EL SAHUARAL", "Tarifa": 250.0, "Distancia": ""},
    {"Destino": "LOS PALMARES", "Tarifa": 300.0, "Distancia": ""},
    {"Destino": "PRADO BONITO", "Tarifa": 230.0, "Distancia": ""},
    {"Destino": "VILLA DORADA 1", "Tarifa": 250.0, "Distancia": ""},
    {"Destino": "VILLADORADA 2", "Tarifa": 250.0, "Distancia": ""},
    {"Destino": "NUEVO EMPALME", "Tarifa": 250.0, "Distancia": ""},
    {"Destino": "LAS JACARANDAS", "Tarifa": 250.0, "Distancia": ""},
    {"Destino": "PANTEON EMPALME", "Tarifa": 230.0, "Distancia": ""},
]



TarifasPorZona = {
    "UTG": ListaUtg,

    "GUAYMAS NORTE": ListaGuaymasNorte,
    "GN": ListaGuaymasNorte,

    "PETROLERA": ListaPetroleraLomaLinda,
    "LA PETRO":ListaPetroleraLomaLinda,
    "PETRO": ListaPetroleraLomaLinda,
    "LOMA LINDA": ListaPetroleraLomaLinda,

    "FOVISSTE": ListaFovissteYAsociadas,
    "LAS JUNTAS": ListaFovissteYAsociadas,
    "LAS AMERICAS": ListaFovissteYAsociadas,
    "LAS PLAZAS": ListaFovissteYAsociadas,
    "LOMA DORADA": ListaFovissteYAsociadas,

    "CENTRO": ListaCentro,

    "GOLONDRINAS": ListaGolondrinasYAsociadas,
    "PTA ARENA":ListaGolondrinasYAsociadas,
    "PUNTA ARENA":ListaGolondrinasYAsociadas,
    "PA": ListaGolondrinasYAsociadas,
    "MONTELOLITA":ListaGolondrinasYAsociadas,
    "TERMOELECTRICA":ListaGolondrinasYAsociadas,

    "SAN VICENTE": ListaSanVicente,
    "SV": ListaSanVicente,

    "18 DE NOVIEMBRE": Lista18Noviembre23Marzo,
    "18 NOV": Lista18Noviembre23Marzo,
    "23 DE MARZO": Lista18Noviembre23Marzo,

    "CENTINELA": ListaCentinelaYAsociadas,
    "AMP INDEP": ListaCentinelaYAsociadas,
    "AMPLIACION INDEPENDENCIA": ListaCentinelaYAsociadas,
    "13 DE JULIO":ListaCentinelaYAsociadas,
    "TETABIATE":ListaCentinelaYAsociadas,

    "MIRADOR": ListaMirador,
}
MapasTarifas = {
    "CENTRO": ListaCentro,
    "GUAYMAS NORTE": ListaGuaymasNorte,
    "PETROLERA / LOMA LINDA": ListaPetroleraLomaLinda,
    "FOVISSTE": ListaFovissteYAsociadas,
    "GOLONDRINAS": ListaGolondrinasYAsociadas,
    "PTA ARENA":ListaGolondrinasYAsociadas,
    "MONTELOLITA":ListaGolondrinasYAsociadas,
    "TERMO":ListaGolondrinasYAsociadas,
    "SAN VICENTE": ListaSanVicente,
    "18 NOVIEMBRE / 23 MARZO": Lista18Noviembre23Marzo,
    "CENTINELA Y ASOCIADAS": ListaCentinelaYAsociadas,
    "AMP. INDEPENDENDENCIA":ListaCentinelaYAsociadas,
    "13 DE JULIO":ListaCentinelaYAsociadas,
    "TETABIATE":ListaCentinelaYAsociadas,
    "MIRADOR": ListaMirador,
    "UTG":ListaUtg,
    "GN - VALLE":ListaGnValle,
    "GN - EMPALME":ListaGnEmpalme,

}

def main(page: ft.Page):
    img = ft.Image(src="icon.png")
    page.title = "Calculadora de Tarifas Guaymas"
    page.bgcolor = COLOR_FONDO_GRIS_PERLADO
    page.padding = 20
    page.theme_mode = ft.ThemeMode.LIGHT

    # --- Variables de Interfaz ---
    TextoTarifa = ft.Text("Tarifa: $0.00", size=24, weight=ft.FontWeight.BOLD, color=COLOR_TEXTO_NEGRO)

    # --- Funciones de Control ---
    def AlCambiarOrigen(e):
        """Actualiza el dropdown de destinos basado en el origen seleccionado."""
        OrigenSeleccionado = DropdownOrigen.value
        if OrigenSeleccionado in MapasTarifas:
            # Obtener la lista de destinos para ese origen
            ListaDestinos = MapasTarifas[OrigenSeleccionado]
            # Limpiar y llenar nuevas opciones
            DropdownDestino.options = [
                ft.dropdown.Option(d["Destino"]) for d in ListaDestinos
            ]
            DropdownDestino.disabled = False
            DropdownDestino.value = None
        else:
            DropdownDestino.options = []
            DropdownDestino.disabled = True

        TextoTarifa.value = "Tarifa: $0.00"
        page.update()

    def CalcularTarifa(e):
        """Busca el precio en la lista correspondiente."""
        Origen = DropdownOrigen.value
        Destino = DropdownDestino.value

        if Origen and Destino:
            ListaActual = MapasTarifas[Origen]
            # Buscar el objeto que coincida con el destino
            Resultado = next((item for item in ListaActual if item["Destino"] == Destino), None)

            if Resultado:
                TextoTarifa.value = f"Tarifa: ${Resultado['Tarifa']:.2f}"
            else:
                TextoTarifa.value = "Destino no encontrado"
        page.update()

    # --- Componentes UI ---
    DropdownOrigen = ft.Dropdown(
        label="Punto de Origen",
        hint_text="¿De dónde sales?",
        options=[ft.dropdown.Option(key) for key in MapasTarifas.keys()],
        on_change=AlCambiarOrigen,
        border_color=COLOR_PRIMARIO_DORADO,
        focused_border_color=COLOR_TEXTO_NEGRO,
        color=COLOR_TEXTO_NEGRO
    )

    DropdownDestino = ft.Dropdown(
        label="Destino",
        hint_text="Selecciona tu destino",
        disabled=True,
        on_change=CalcularTarifa,
        border_color=COLOR_PRIMARIO_DORADO,
        focused_border_color=COLOR_TEXTO_NEGRO,
        color=COLOR_TEXTO_NEGRO,
        width=270,

    )
    # --- Diseño de la Pantalla ---
    ContenedorPrincipal = ft.Container(
        content=ft.Column(
            [
                # 1. Logo al principio
                ft.Image(
                    src="icon.png",
                    width=100,
                    height=100,
                    fit=ft.ImageFit.CONTAIN
                ),
                # 2. Título de la empresa
                ft.Text("ÈLITE TRAVEL", size=28, weight=ft.FontWeight.BOLD, color=COLOR_PRIMARIO_DORADO),
                ft.Divider(color=COLOR_PRIMARIO_DORADO, thickness=2),

                # 3. Instrucciones y selección
                ft.Text("Selecciona los puntos de tu viaje:", color=COLOR_TEXTO_SECUNDARIO),
                DropdownOrigen,
                DropdownDestino,

                # 4. Espaciador y Cuadro de Tarifa
                ft.Container(height=10),
                ft.Container(
                    content=TextoTarifa,
                    padding=20,
                    bgcolor=COLOR_PRIMARIO_DORADO,
                    border_radius=10,
                    alignment=ft.alignment.center
                ),
            ],
            horizontal_alignment=ft.CrossAxisAlignment.CENTER,
            spacing=15
        ),
        padding=30,
        bgcolor=COLOR_FONDO_CARD,
        border_radius=15,
        shadow=ft.BoxShadow(blur_radius=10, color=ft.Colors.BLACK12),
        width=450
    )

    page.add(ft.Row([ContenedorPrincipal], alignment=ft.MainAxisAlignment.CENTER))

# Ejecutar la aplicación
if __name__ == "__main__":
    ft.app(target=main, assets_dir="assets")